# Generated by Django 2.2.10 on 2020-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_auto_20200807_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
